name: CI

on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -   name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 'lts/*'
      -   name: Install Node dependencies
          run: npm install
      -   name: Grant execute permission for set-version
          run: chmod +x set-version
      -   name: Release
          run: npm run release
